server:
  port: 8080

spring:

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /static/**
  main:
    allow-circular-references: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shixun?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1535926365
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5

      idle-timeout: 1800000

      maximum-pool-size: 10

      auto-commit: true
      max-lifetime: 1800000

      connection-timeout: 3000

      connection-test-query: SELECT 1

  web:
    resources:
      add-mappings: true
      cache:
        cachecontrol:
          max-age: 3600
      chain:
        cache: true

        enabled: true

        compressed: true


      static-locations: classpath:/static/




#mybatis
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.example.shixun2.bean
